### ISSUE TITLE
Filter out "default integrations" from integration list

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/analytics.home-assistant.io#22]
Great idea / improvement!

Would it be an idea to be able to "filter out default integrations" - integrations that HA always loads - in the list of integration usage? Reason for bringing this up is that some integrations will always hog the first few lines as they are always (or almost always) loaded with HA (i.e. auth, zone, websocket, frontend etc)

Looking at the list now, this would for instance at least skip the first 23 lines potentially even more.

I am thinking of a checkbox style kind of thing, which upon selection removes the "ha default integrations" out of the list in the users browser. All at the user side - I am not suggesting to remove the data from the backend, just filter it in the frontend list when the box is ticked.

**Comment by ludeeus** [comment]
Hiding defaults from the portal are already in the works <https://github.com/home-assistant/analytics.home-assistant.io/pull/17>.

We use Github to track issues, if that PR does not cover your need, feel free to open a Feature Request on the forums :+1:

**Comment by hmmbob** [comment]
Totally missed that one 😬 

Thanks Joakim!
