### ISSUE TITLE
New history graph shows past 17 hours

### ISSUE THREAD

**Issue by TheZoker** [home-assistant/analytics.home-assistant.io#260]
Is it wanted, that the new history graph only shows past 17 hours?

I think that it might be more useful, to show 7 days here or something. Otherwise the graphs will mostly be flat lines (except maybe for release day)
![image](https://user-images.githubusercontent.com/1368405/127648347-be2e735a-7084-4a8d-9fb3-ec39488ed293.png)

**Comment by bramkragten** [comment]
There is not more data ATM, it was just added

**Comment by TheZoker** [comment]
So the graph will expand over time, right?

**Comment by ludeeus** [comment]
Yes, it's updated every hour.
The data show was there before as well, but not in a way we could get/display like this, that was added in #218.
So it will only show datapoints from the first hour after that change was added to the `main` branch.
