### ISSUE TITLE
Ensure consistent decimals + blank before "%"

### ISSUE THREAD

**Issue by spacegaier** [home-assistant/analytics.home-assistant.io#278]
https://github.com/home-assistant/analytics.home-assistant.io/blob/e69ac5a3a3d54d245fbfe7d73c49ee4fdd415bb6/site/src/analytics-integrations.ts#L147-L150

Having consistent decimals would make the list rendering a bit nicer.
![image](https://user-images.githubusercontent.com/114137/128646510-d890bf21-09f5-40c9-b4c8-0bc4e78e64f0.png)

Not really sure if an explicit `Number()` conversion is required for the decimal to be guaranteed. In the browser console this seems to behave correctly:
```console.log(((22369 * 100) /  58815).toFixed(1));```

Also having a blank in front of the "%" would match what we do in the HA frontend and I think is the official ISO/DIN/... style.

**Comment by ludeeus** [comment]
The space is fine to add.
The extra decimal, I'm not too sure about.
What about 100 %?, or < 10 %? those will still be rendered differently, I personally don't see a need for a decimal when the value of that decimal is 0

**Comment by spacegaier** [comment]
I am coming from the point of visual consistency. I don't like values in tables "flopping" around and destroying a visual coherent rendering, which is what happens without the 0 decimal. It just looks a bit unrefined to me.

@matthiasdebaat What does the UX theory say here?

**Comment by matthiasdebaat** [comment]
A best practice is to always use the same value in a list and align it. In this case I would suggest adding the `.0%` and aligning the numbers and percentage for easy readability.
