### ISSUE TITLE
Coloring scale of world map by population

### ISSUE THREAD

**Issue by ThomDietrich** [home-assistant/analytics.home-assistant.io#410]
Hey there,
I got curious about the Analytics world map presentation. Why is the US in darkest color? Turns out the countries are colored by absolute installation. That imho doesn't make sense. You should either divide by area or population to generate a more representative view.

https://github.com/home-assistant/analytics.home-assistant.io/blob/9d1790e85af868e20a47b4f643236358102e2887/site/src/analytics-map.ts#L32

I personally would go with the population of countries and there are many good sources for country population online, e.g. https://www.kaggle.com/erikbruin/countries-of-the-world-iso-codes-and-population?select=country-and-continent-codes-list-csv.csv

Best!

**Comment by ludeeus** [comment]
There is an open feature request for this here <https://community.home-assistant.io/t/per-capita-option-in-statistics-world-map/353611>, add your vote to it :+1:
