### ISSUE TITLE
Custom Components Analytics is missing (Feature Request)

### ISSUE THREAD

**Issue by ReneNulschDE** [home-assistant/analytics.home-assistant.io#427]
Hi team,

first of all a big thank you - the overall Home Assistant environment is fantastic. I saw in the logs that you collect custom component usage data too.

Would be good to see this in the analytics portal. This would help the hundreds of custom component developers (like me with [my mercedes benz integration](https://community.home-assistant.io/t/mercedes-me-component/41911/1024)) to get a better usage understanding too.

Thanks
Rene

**Comment by ludeeus** [comment]
Custom integrations are not supported by Home Assistant, so they will not be shown in the portal like core integrations.
You can however have a look here <https://analytics.home-assistant.io/custom_integrations.json> it will show all custom integration that is in use by users that have opted-in to share integrations if the integration also has a [brands image](https://github.com/home-assistant/brands) submitted.
