### ISSUE TITLE
Todoist component not showing correct number of installations

### ISSUE THREAD

**Issue by marciogranzotto** [home-assistant/analytics.home-assistant.io#428]
I was checking the Todoist component docs for an unrelated issue, and I noticed that it shows 0 active installations.
That is clearly wrong since at least mine integration show be showing up hahaha

```yaml
calendar:
  - platform: todoist
    token: !secret todoist_token
```

![image](https://user-images.githubusercontent.com/11080704/144076044-0667772b-1c4c-4bba-8f2e-a1dc77a3abfb.png)

![image](https://user-images.githubusercontent.com/11080704/144076248-1cd74000-4ff2-4cd0-8da4-4e0dc0bb779a.png)

I'm using that integration for several months, so I guess it should be showing up in the analytics

**Comment by balloob** [comment]
I wonder if this is happening because it's configured as a platform and not an integration/config entry.
