### ISSUE TITLE
Data missing from usage statistics

### ISSUE THREAD

**Issue by bdr99** [home-assistant/analytics.home-assistant.io#517]
The usage statistics for integrations and add-ons seem to have dropped suddenly and drastically. The most popular integration is showing only 1260 installs.

![image](https://user-images.githubusercontent.com/2292715/164367644-08ffcb6e-db1e-4cb7-8380-9d2eb2cc3465.png)

**Comment by ludeeus** [comment]
There was an issue with the calculating handler last week, this has been resolved.
