### ISSUE TITLE
Missing country field in Basic Analytics

### ISSUE THREAD

**Issue by Luki72** [home-assistant/analytics.home-assistant.io#56]
Hi everyone,

I recently upgraded to 2021.4.0 and enabled analytics, but az I can see country info is missing in sent data:

`2021-04-07 22:15:09 INFO (MainThread) [homeassistant.components.analytics] Submitted analytics to Home Assistant servers. Information submitted includes {'uuid': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'version': '2021.4.0', 'installation_type': 'Home Assistant Supervised', 'supervisor': {'healthy': True, 'supported': True}}`

Documentation says IP address derived server-side from the IP address, but my HA runs on Debian in Docker container and both the host system and the container have private IP addresses. So is this the reason? Or can someone tell me how the IP address really derived?

Thank you in advance for the answers.

**Comment by spacegaier** [comment]
Well even if HA itself has a private IP address (as most instances do), at some point in the communication chain to the HA analytics server, there has to be a public IP that you use from your ISP. That one is the one then used for the country determination.

**Comment by ludeeus** [comment]
The analytics backend runs in Cloudflare's network, they attach the country-code to all pages/services served in that network.

**Comment by Luki72** [comment]
I see, everything is clear now. 

THX guys!
