### ISSUE TITLE
Active Installations - Installation Type graph has flatlined

### ISSUE THREAD

**Issue by Didgeridrew** [home-assistant/analytics.home-assistant.io#62]
The graph at https://analytics.home-assistant.io/#installations is partially broken... more than 3000 additional users since yesterday, but the installation types numbers have not changed.

**Comment by frenck** [comment]
![image](https://user-images.githubusercontent.com/195327/114039515-18d9d980-9883-11eb-93bd-d4f3db83071f.png)
