### ISSUE TITLE
Google Translate & Microsoft TTS show as 0 installs

### ISSUE THREAD

**Issue by hmmbob** [home-assistant/analytics.home-assistant.io#65]
The analytics page shows that the ` Google Translate TTS` and ` Microsoft TTS` and other TTS integrations have 0 installs - which deemed odd. I think the numbers are actually included in the ` tts` integration. I know for sure both should have at least 1 install (being mine ;-) )

![image](https://user-images.githubusercontent.com/33529490/114158116-a3264a00-9924-11eb-9b06-e77268ddeb86.png)

**Comment by ludeeus** [comment]
The website does not do anything with this.
Are you r instance actually sending it?

**Comment by hmmbob** [comment]
it should be, ticked all boxes.

But - I can't imagine that I'm the only user of these integrations.... Hence my feeling that they are embedded in the TTS side - maybe in the analytics reporting already.

**Comment by ludeeus** [comment]
Must be a bug with the integration then, can you open an issue here <https://github.com/home-assistant/core/issues/new?assignees=&labels=&template=bug_report.yml&title=> ?
And provide the log message that the analytics integration prints when it sends the data (but remove your uuid from it before pasing)

**Comment by hmmbob** [comment]
Will do. I don't see the log message yet, so I'll reboot with logger set to info later today (it's set to `warn` here)

**Comment by ludeeus** [comment]
```
logger:
  default: warn
  logs:
    homeassistant.components.analytics: info
 ```
You can use this
