### ISSUE TITLE
Add statistics for custom integrations

### ISSUE THREAD

**Issue by PiotrMachowski** [home-assistant/analytics.home-assistant.io#66]
It would be nice to see statistics for custom integrations as well.

In a discussion on HA forum @spacegaier [mentioned that this might be dangerous](https://community.home-assistant.io/t/2021-4-for-our-advanced-users/297058/367), as custom components are not validated, but I think this risk can be neutralized by limiting shown custom integrations e.g. to ones available in [home-assistant/wheels-custom-integrations](https://github.com/home-assistant/wheels-custom-integrations) or [home-assistant/brands](https://github.com/home-assistant/brands/tree/master/custom_integrations/).

**Comment by ludeeus** [comment]
We use GitHub to track issues, please open a freature request on the forum, thanks 👍

**Comment by PiotrMachowski** [comment]
Whoops, sorry

**Comment by PiotrMachowski** [comment]
Whoops, sorry.

[FR on forum](https://community.home-assistant.io/t/add-statistics-for-custom-integrations-on-home-assistant-analytics/297600)
