### ISSUE TITLE
Visualize database engine & version

### ISSUE THREAD

**Issue by Skaronator** [home-assistant/analytics.home-assistant.io#696]
It would be cool to visualize the newly gathered database engine and version on the analytics page.

---

Additionally, the information about the new database information is not listed in the documentation. @ludeeus

https://www.home-assistant.io/integrations/analytics 

Ref:

- https://github.com/home-assistant/analytics.home-assistant.io/pull/688
- https://github.com/home-assistant/core/pull/87784

**Comment by ludeeus** [comment]
Use forums for feature requests.
