### ISSUE TITLE
analytics.home-assistant.io - Home Assistant Analytics website no longer hides system integrations

### ISSUE THREAD

**Issue by Hedda** [home-assistant/analytics.home-assistant.io#748]
Bug? Home Assistant Analytics website (analytics.home-assistant.io) no longer hides system default integrations on statistics page:

https://analytics.home-assistant.io/integrations/

@ludeeus Before PR https://github.com/home-assistant/analytics.home-assistant.io/pull/648 was merged as part of https://github.com/home-assistant/analytics.home-assistant.io/pull/746 the filter hide system default integrations on the statistics page so that it did not show system integrations like; Webhook, Sun, Tags, Mobile App, Input Boolean, Input Number, etc.

This now makes the integrations page on the Home Assistant Analytics website show many system integrations that are IMHO probably not of much interest to most users and companies looking at that page for quick statics to see which IoT protocols and ecosystems are popular and promoted, like example; ESPHome, MQTT, Zigbee, Z-Wave, Matter, and Bluetooth, etc.

https://www.home-assistant.io/integrations/

It does no longer make sense with what was previously said that analytics would be used to promote integrations to and for manufacturers of IoT products who might be interested in joining the "Works with Home Assistant program" partner program:

https://www.home-assistant.io/blog/2021/11/12/100k-analytics/

https://www.home-assistant.io/blog/2022/07/12/partner-program/

https://partner.home-assistant.io/

# Before 

![image](https://github.com/home-assistant/home-assistant.io/assets/6320001/577b557a-8458-4072-9d61-c6fed7635f01)

# Now

![image](https://github.com/home-assistant/home-assistant.io/assets/6320001/3987a416-5594-429d-a744-c918d042388f)

**Comment by frenck** [comment]
System integrations are now show, they are not part of the list:

![CleanShot 2023-06-22 at 11 41 30](https://github.com/home-assistant/analytics.home-assistant.io/assets/195327/b166cffb-72c7-4ac3-8fbf-80e729615132)

I think your definition of "system integrations" is not right?

We are looking into making analytics more aware of "loaded" vs "usage", but that might be a good next step. As for system integrations being shown as mentioned in this issue, that is not correct. For example, Webhook, Sun, Tags, Mobile App, Input Boolean, Input Number are normal integrations and some are helpers.

../Frenck
