### ISSUE TITLE
Filter is not working

### ISSUE THREAD

**Issue by EvertJob** [home-assistant/analytics.home-assistant.io#769]
Hi,

I was looking on https://analytics.home-assistant.io/integrations/ for a specific intergration ("Alert") but the search bar don't work.

**Comment by ludeeus** [comment]
It works, maybe you have blocked javascript in your browser
![image](https://github.com/home-assistant/analytics.home-assistant.io/assets/15093472/9be376a6-feb0-4fc0-ad03-a1ee13741816)

**Comment by EvertJob** [comment]
Yep. Tried 3 devices, all the same result. Now it's filtering again!
